spring:
  datasource:
    url: jdbc:mysql://35.194.191.129:3306/test?useUnicode=true&characterEncoding=utf8
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    #   database: 0
    host: 114.116.155.42
    port: 6379
    password: metetordog2017DEDC
    timeout: -1
    pool:
      max-active: 8
      max-wai: -1
      max-idle: 8
      min-idle: 0